### ISSUE TITLE
Unable to work

### ISSUE THREAD

**Issue by just808b** [alxscms/homebridge-somfy-protect#12]
Hi,

I am using Hoobs to add the Somfy plug-in.  I have tried the multi and the single Somfy plug-in, which both do add to HomeKit, but I am unable to arm or disarm and it’s stats ‘no response’ in HomeKit.  The error logs are attached.  The statement in red is in response to me asking to arm or disarm the security system. 
![D4931EA2-A22D-4578-A00B-0AEC40ACAB3E](https://user-images.githubusercontent.com/84090729/128879627-5ec33b4e-c1a3-41c6-8edc-16cdef0372bb.jpeg)

can you help?

**Comment by RedPanda8787** [comment]
@just808b Hello, I am having the same issue unfortunately.
Were you able to find a solution in the meantime or you are still waiting for an answer? 
Thanks a lot in advance!

**Comment by just808b** [comment]
I’m still waiting. I wish I could code to edit what was required myself, as I’m missing setting my alarm as part of my Good Night scene.

**Comment by RedPanda8787** [comment]
@just808b same same, I would love to add it to my Homekit automations and avoid having to run 2 apps separatly… 
Thanks anyway!

**Comment by alxscms** [comment]
Hi, I am not using hoobs myself so it might be difficult for me to help debug your situation, however I can see in the logs you attached "Somfy Protect Bridge 2": what is it ? Are you using my plugin with an other one ?

**Comment by RedPanda8787** [comment]
Hi @alxscms and thank you for your answer :)
Hoobs is simply a homebridge solution preinstalled on a sd card or raspberry. They also have a cleaner/easier to use interface I find, but its homebridge behind.
On hoobs you need to create at least a bridge to install your plugins but I guess the idea is to create silos between the different plugins in case something goes wrong.

**Comment by just808b** [comment]
This has only happened since the recent upgrade from Hoobs, where each plug-in now as it’s own bridge.  In this instance ‘Somfy Protect Bridge 2’. I have tried renaming the bridge, adding the plug-in to another existing bridge, removing every plugin and only install the somfy plug-in with one bridge and Resetting the entire device and install fresh.  All results in the same error.

**Comment by alxscms** [comment]
Ok thanks for the details, it helps me a lot :)
It seems that the way hoobs work in the version 4 with the bridges like you describe them is the reason why it fails on hoobs and not on homebridge. Sadly hoobs do not support yet mac os to run hoobs natively (so that I can reproduce the bug as I don't have a hoobs box). However I might have found why the plugin is raising following error:
```
ERROR [Somfy Protect Bridge 2 3743@Somfy Protect@Somfy Protect@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response
```
I have made a beta version to attempt solving the problem (again I'm definitely not sure it will as I can't reproduce myself the problem). The version number is `1.1.1-beta.0`. If you can npm install on hoobs the command would be `npm install homebridge-somfy-protect@1.1.1-beta.0`. Hopefully it works 🤞

The warning you have however seems like your credentials for your somfy account are not correct. Is it the case ?

**Comment by just808b** [comment]
Thankyou.  I have downloaded the beta in Hoobs.  Adds to HomeKit ok, the same error no longer shows.  But a new error.  I hope it’s something simple. 

![1AEEC18A-FC11-4DB5-9EA5-36F47EF5090D](https://user-images.githubusercontent.com/84090729/143091885-db273004-12e3-4946-a7e6-143fb5475a8b.jpeg)

n.b.  The credentials are correct.

**Comment by alxscms** [comment]
Hi,
I think I have found a solution to fix the error you have (can't still figure out why I didn't have it...). You can test with this new beta version : [1.1.1-beta.2](https://www.npmjs.com/package/homebridge-somfy-protect/v/1.1.1-beta.2).
Please tell me if it finally works as intended so that I can release everything in a non beta version later on.

**Comment by alxscms** [comment]
I have released the beta version in the version 1.1.2 of the plugin. Everything should work for you now. If not, don't hesitate to comment here and I will reopen the issue.

**Comment by RedPanda8787** [comment]
Hello Alexis,

I searched for your latest version but I can only see the 1.1.0 version so far.
Is it limited to an older version of Homebridge?

Thanks a lot in advance!

Alex

**Comment by RedPanda8787** [comment]
Hi @just808b !
Have you been able to make it work on Hoobs? 
If you did; can you please tell me how you installed it? 
Thanks a lot in advance!

**Comment by alxscms** [comment]
The version 1.1.2 is published on npm just like all other versions, you should have access to it normally. Here is the direct link on npm : [https://www.npmjs.com/package/homebridge-somfy-protect/v/1.1.2](https://www.npmjs.com/package/homebridge-somfy-protect/v/1.1.2).
If you have the 1.1.1 installed, it is almost exactly the same, I have just fixed a log that should not be visible in some cases in 1.1.2. It does not improve anything other than that. Do you still have problems with the 1.1.1 version ?

**Comment by RedPanda8787** [comment]
Ok thanks for the swift response! I will check this again ;)
I guess I can only install it through the terminal right?
Cheers,
Alex

**Comment by alxscms** [comment]
Never used hoobs, but it seems that you can install a specific version through the interface, see here: [https://support.hoobs.org/docs/60e0cdc7646faaa152f10dd9#plugin-versions](https://support.hoobs.org/docs/60e0cdc7646faaa152f10dd9#plugin-versions)

**Comment by just808b** [comment]
> Hi @just808b !
> Have you been able to make it work on Hoobs?
> If you did; can you please tell me how you installed it?
> Thanks a lot in advance!

I have done a couple of screenshot for you.  Click on where I have circled red. Be interesting to see if you get the same error, or if it works? 
![CCB4DDD0-BD2B-4C33-A22B-B72529CDA605](https://user-images.githubusercontent.com/84090729/144097339-327fb451-86d4-4259-b7d0-7b86da0e0b1d.jpeg)
![B4FC4799-C820-4184-8523-C4967346C6D0](https://user-images.githubusercontent.com/84090729/144097345-a9d84d8a-d85f-4172-a126-9ff54c5e8e98.jpeg)

**Comment by just808b** [comment]
> Hi,
> I think I have found a solution to fix the error you have (can't still figure out why I didn't have it...). You can test with this new beta version : [1.1.1-beta.2](https://www.npmjs.com/package/homebridge-somfy-protect/v/1.1.1-beta.2).
> Please tell me if it finally works as intended so that I can release everything in a non beta version later on.

This new beta version 1.1.1-beta.2 is not available, these are the versions available (please ignore red circle) 
![B32AA61E-8264-4DA6-A38F-8FC12A9CDC81](https://user-images.githubusercontent.com/84090729/144098758-85c162a9-8d0a-4db8-966c-8d2503a4cf4b.jpeg)

**Comment by just808b** [comment]
A clearer screenshot showing only v 1.1.1 available 
![B28CAC3F-B284-473E-A335-1B192DBE2F41](https://user-images.githubusercontent.com/84090729/144099057-b4745752-50fd-44b8-b9f9-f15f757379d7.jpeg)

**Comment by alxscms** [comment]
It's very weird, it appears that hoobs did not get all the new versions for the plugins. You should try maybe to remove the plugin completely and put it back. Or reboot hoobs.
As a last resource you could maybe update it using command line. See on non for all the available version, the latest one should be 1.1.2.

**Comment by RedPanda8787** [comment]
Very weird indeed, I checked again this morning, and even after deleting the plugin and the hub, I am still left with no access to further version than 1.1.1 beta 0 :/

**Comment by RedPanda8787** [comment]
Hello,

I just did a factory reset of hoobs and updated it to the latest firmware (which should also be aligned with the latest Homebridge version I suppose) and I still can’t see the version 1.1.2 of your plugin… :(

Do you think it might be related to the way you published it, is there anything different to the previous versions by any chance?

Sorry I am not very tech savvy…

Thanks again for your patience and your help, it is really appreciated :)

**Comment by alxscms** [comment]
Hi, thanks to you for trying out ways to resolve the problem. Unfortunately I haven't done anything different than before when publishing on npm the latest versions. I have unpublished all beta versions, so they should not appear anymore in your interface (but we never know).

The last thing you could try is to install the 1.1.2 manually with command line. Tell me how it goes :)

**Comment by RedPanda8787** [comment]
Ok, maybe I should try this. 
The terminal doesn’t seem accessible though, I suspect a bug on Hoobs’ side.
What would be the procedure otherwise?

Sorry for taking so much of your time….

Alex

**Comment by RedPanda8787** [comment]
Hello,

Have you been able to make it work on your end?
Have a nice weekend!

Alex

**Comment by just808b** [comment]
I have contacted Hoobs as the old Beta version is still showing (last
update is 22nd November).   Also, I have no idea how to use command lines
to install the new one, so asked how this is possible.

Close, but no cigar.

**Comment by RedPanda8787** [comment]
Alright! Thanks for the update 😊
Have a great weekend and let’s hope we can soon get this sorted out!

Have a good weekend,

Alex

**Comment by just808b** [comment]
Update: had an email from them.

‘We are working on resyncing the plugin site. It seems like some plugins
have been missed by the automated process. The update should be available
soon.’

Best

**Comment by just808b** [comment]
Ovi from Hoobs has been in touch, stating all should be ok.  If any problem to clear cache. 

I have downloaded the latest version (v.1.1.2) and it works perfect.  Also love the new multiple home ID you have set up.  This is extremely helpful to me as well.

**Comment by RedPanda8787** [comment]
Sweeet!
Thanks for the update guys 🥳
Have a great weekend ☃️

Alex

**Comment by RedPanda8787** [comment]
I just installed it and it works like a charm 🎉
Thank you very much for the plugin Alxscms 😊

Alex

**Comment by alxscms** [comment]
That's perfect ! Happy it finally works for you guys :) enjoy !
