### ISSUE TITLE
probleme config

### ISSUE THREAD

**Issue by kptainigloo** [alxscms/homebridge-somfy-protect#15]
bonjour @alxscms,

je me permet de venir vers toi, car j'ai un soucis de configuration. Quand je rentre mon username et mon mot de passe et que je redémarre Homebridge, il se passe rien dans mon HomeKit.
Le username correspond bien a l'adresse mail de mon compte Somfy ?
Merci de ta réponse.
Cordialement

**Comment by alxscms** [comment]
Salut @kptainigloo ,
Oui normalement c'est l'adresse e-mail et le mot de passe de ton compte Somfy. Tu n'as aucune erreur dans les logs ?

**Comment by kptainigloo** [comment]
Merci de ta réponse @alxscms. Non j’ai pas d’erreur dans les logs et quand je redémarre le serveur, j’ai pas d’adresse mail ni de mot de passe des les codes du plugin.

**Comment by alxscms** [comment]
Tu veux dire que la config que tu as renseignée pour le plugin est perdue lorsque tu redémarre ton serveur homebridge ?

**Comment by kptainigloo** [comment]
Oui en gros c’est ça. Et après j’ai pas de trace du plugin dans les logs

**Comment by kptainigloo** [comment]
@alxscms as tu une solution ?

**Comment by alxscms** [comment]
Aucune idée non désolé :/ as tu trouvé une solution au final ?
