### ISSUE TITLE
Error integration

### ISSUE THREAD

**Issue by thierrysoler** [alxscms/homebridge-somfy-protect#26]
Hi
When I tried to integrate with :

Home Assistant 2023.4.6

Supervisor 2023.04.1

Operating System 10.1

Interface utilisateur : 20230411.1 - latest

and :

HACS Version : 1.32.1
I get the error : <Integration alxscms/homebridge-somfy-protect> Repository structure for master is not compliant

Thank you
Best regards

Thierry

**Comment by alxscms** [comment]
Hi,
I do not use Home Assistant, so I can't help you with that. However maybe you can check this thread https://community.home-assistant.io/t/repostitory-structure-for-is-not-compliant/295074
If you want to make a PR if the issue comes from this repo, feel free to do it.
