### ISSUE TITLE
Information about the code.

### ISSUE THREAD

**Issue by Minims** [alxscms/homebridge-somfy-protect#7]
Can you tell me where does this comes from ? 
Is it you own application on myfox or the one used by the somfy app you reverse engineered ? 

Thanks !

```
const CLIENT_ID = "84eddf48-2b8e-11e5-b2a5-124cfab25595_475buqrf8v8kgwoo4gow08gkkc0ck80488wo44s8o48sg84k40";
const CLIENT_SECRET = "4dsqfntieu0wckwwo40kw848gw4o0c8k4owc80k4go0cs0k844";
```

**Comment by alxscms** [comment]
It's supposed to be the same ID and SECRET for everyone. I have found it in other libraries trying to connect to Somfy APIs. I do not really remember which library I got them from, sorry...
